name:                advent-twentytwenty
version:             0.1.0.0
github:              "githubuser/advent-twentytwenty"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2020 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/advent-twentytwenty#readme>

dependencies:
- base >= 4.7 && < 5
- megaparsec
- text

library:
  source-dirs: src

executables:
  advent-twentytwenty-day1:
    main:                Main.hs
    source-dirs:         app/Day01
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - advent-twentytwenty

  advent-twentytwenty-day2:
    main:                Main.hs
    source-dirs:         app/Day02
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - advent-twentytwenty

  advent-twentytwenty-day3:
    main:                Main.hs
    source-dirs:         app/Day03
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - advent-twentytwenty

  advent-twentytwenty-day4:
    main:                Main.hs
    source-dirs:         app/Day04
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - advent-twentytwenty

  advent-twentytwenty-day5:
    main:                Main.hs
    source-dirs:         app/Day05
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - advent-twentytwenty

tests:
  advent-twentytwenty-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - advent-twentytwenty
